name: CI

on: [pull_request]

jobs:
  SwiftLint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: SwiftLint
        uses: norio-nomura/action-swiftlint@3.1.0
        with:
          args: --strict

  macOS:
    runs-on: macos-13
    env:
      XCODE_VERSION: ${{ '15.0' }}
    steps:
      - name: Install nginx
        run: "brew install nginx"
      - name: Select Xcode
        run: "sudo xcode-select -s /Applications/Xcode_$XCODE_VERSION.app"
      - name: "Install iOS SDK"
        run: "xcodebuild -downloadPlatform iOS"
      - name: "Install watchOS SDK"
        run: "xcodebuild -downloadPlatform watchOS"
      - name: Checkout
        uses: actions/checkout@v1
      - name: Build and Run
        run: rake build[release]
      - name: Test
        run: rake test
      - name: E2ETests
        run: rake e2e_only
