name: CI

on: [pull_request]

jobs:
  # SwiftLint:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v1
  #     - name: SwiftLint
  #       uses: norio-nomura/action-swiftlint@3.1.0
  #       with:
  #         args: --strict

  # macOS:
  #   runs-on: macOS-latest
  #   env:
  #     XCODE_VERSION: ${{ '13.1' }}
  #   steps:
  #     - name: Select Xcode
  #       run: "sudo xcode-select -s /Applications/Xcode_$XCODE_VERSION.app"
  #     - name: Checkout
  #       uses: actions/checkout@v1
  #     - name: Build and Run
  #       run: rake build[release]
  #     - name: Test
  #       run: rake test
  #     - name: E2ETests
  #       run: rake e2e_only
    
  docs:
    runs-on: macos-12
    env:
      XCODE_VERSION: ${{ '13.3.1' }}
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
          fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.
      - name: Select Xcode
        run: "sudo xcode-select -s /Applications/Xcode_$XCODE_VERSION.app"
      - name: "Generate documentation"
        run: "swift package --allow-writing-to-directory ./docs  generate-documentation --target XCRemoteCache --disable-indexing --transform-for-static-hosting --output-path ./docs  --hosting-base-path XCRemoteCache/"
      - name: Deploy GH-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          keep_files: false
