name: "CodeQL"

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  run-codeql-macos:
    name: Run CodeQL on MacOS
    runs-on: macos-12
    permissions:
      security-events: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v2
      with:
        languages: swift

    - name: Build
      run: swift build

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v2